### ISSUE TITLE
Heroku Crashing

### ISSUE THREAD

**Issue by Christopher-Chianelli** [Christopher-Chianelli/timebot#1]
Whenever timebot is launched from Heroku, it crashes. I cannot decipher the log files to find the issue.

Example Log:
2016-07-20T22:38:52.045642+00:00 heroku[hubot.1]: Starting process with command `bin/hubot --adapter slack`
2016-07-20T22:38:52.713483+00:00 heroku[hubot.1]: State changed from starting to up
2016-07-20T22:38:57.919668+00:00 app[hubot.1]: [Wed Jul 20 2016 22:38:57 GMT+0000 (UTC)] INFO Logged in as timebot of OBNS
2016-07-20T22:38:58.098472+00:00 app[hubot.1]: [Wed Jul 20 2016 22:38:58 GMT+0000 (UTC)] INFO Slack client now connected
2016-07-20T22:38:58.110520+00:00 app[hubot.1]:   at Object.<anonymous> (/app/scripts/slack.coffee:2:12, <js>:4:14)
2016-07-20T22:38:58.110538+00:00 app[hubot.1]:   at Module.require (module.js:364:17)
2016-07-20T22:38:58.110539+00:00 app[hubot.1]:   at Robot.loadFile (/app/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
2016-07-20T22:38:58.110539+00:00 app[hubot.1]:   at Robot.load (/app/node_modules/hubot/src/robot.coffee:377:9, <js>:247:30)
2016-07-20T22:38:58.110540+00:00 app[hubot.1]:   at SlackBot.loadScripts (/app/node_modules/hubot/bin/hubot:93:5, <js>:97:13)
2016-07-20T22:38:58.110541+00:00 app[hubot.1]:   at SlackBot.g (events.js:180:16)
2016-07-20T22:38:58.110541+00:00 app[hubot.1]:   at SlackBot.emit (events.js:92:17)
2016-07-20T22:38:58.110542+00:00 app[hubot.1]:   at SlackBot.open (/app/node_modules/hubot-slack/src/bot.js:55:19)
2016-07-20T22:38:58.110543+00:00 app[hubot.1]:   at RTMClient.emit (/app/node_modules/hubot-slack/node_modules/@slack/client/node_modules/eventemitter3/index.js:115:35)
2016-07-20T22:38:58.110544+00:00 app[hubot.1]:   at RTMClient.emit (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/client.js:83:39)
2016-07-20T22:38:58.110544+00:00 app[hubot.1]:   at RTMClient._handleHello (/app/node_modules/hubot-slack/node_modules/@slack/client/lib/clients/rtm/client.js:613:8)
2016-07-20T22:38:59.097452+00:00 heroku[hubot.1]: Process exited with status 1
2016-07-20T22:38:59.106973+00:00 heroku[hubot.1]: State changed from up to crashed

**Comment by Christopher-Chianelli** [comment]
Issue was with slack.coffee; removed it for the time being
